name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Build & start server
        run: pnpm build && pnpm start
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          env: configFile=ci
          run: pnpm tests:run:ci
          wait-on: 'http://localhost:3000'
          browser: chrome
          record: false

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm i

      - name: Run typecheck
        run: pnpm typecheck

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm i

      - name: Run formatter
        run: pnpm format
